### ISSUE TITLE
FIX: 滑动不跟手

### ISSUE THREAD

**Issue by amazingCoding** [JeremyMing/scrolle_bottom_sheet#1]
跑了一下代码，会出现整体下拉的时候不跟手。
这是由于 ```ModalBottomSheet``` 本来就有 Drag 的下拉动画，而 AnimatedContainer 也进行下拉动画，因此整体面板下降比手指
下降的快。
建议在 ```showModalBottomSheet``` 的时候添加 ```enableDrag: false```

**Comment by JeremyMing** [comment]
感谢分享！

**Comment by JeremyMing** [comment]
> 

感谢分享！
